/**
 * Predefined optimization strategies
 */

import type { OptimizationStrategy } from './types';

export const OPTIMIZATION_STRATEGIES: OptimizationStrategy[] = [
  {
    id: 'memory-cleanup',
    name: 'Automatic Memory Cleanup',
    description: 'Automatically clean up unused memory allocations and optimize garbage collection',
    category: 'memory',
    priority: 'high',
    impact: 'high',
    effort: 'low',
    targetMetrics: ['memoryUsage', 'memoryPressure'],
    implementation: [
      'Clear image caches when memory pressure is high',
      'Dispose of unused React components and listeners',
      'Clean up temporary data structures',
      'Force garbage collection in controlled manner',
    ],
    automated: true,
    enabled: true,
  },
  {
    id: 'lazy-loading',
    name: 'Intelligent Lazy Loading',
    description: 'Load components and data only when needed to improve startup time',
    category: 'rendering',
    priority: 'high',
    impact: 'high',
    effort: 'medium',
    targetMetrics: ['appStartTime', 'firstScreenRenderTime'],
    implementation: [
      'Lazy load non-critical screens using React.lazy',
      'Defer heavy computations until after initial render',
      'Load country schemas on-demand',
      'Use intersection observers for list items',
    ],
    automated: true,
    enabled: true,
  },
  {
    id: 'form-caching',
    name: 'Smart Form Caching',
    description: 'Cache frequently used form data and schemas to reduce generation time',
    category: 'data',
    priority: 'medium',
    impact: 'medium',
    effort: 'low',
    targetMetrics: ['formGenerationTime'],
    implementation: [
      'Cache parsed country schemas',
      'Memoize auto-fill calculations',
      'Pre-compute common form configurations',
      'Use React.memo for form components',
    ],
    automated: true,
    enabled: true,
  },
  {
    id: 'database-optimization',
    name: 'Database Query Optimization',
    description: 'Optimize database queries and add strategic indexes',
    category: 'data',
    priority: 'medium',
    impact: 'medium',
    effort: 'medium',
    targetMetrics: ['databaseQueryTime'],
    implementation: [
      'Add indexes for frequently queried fields',
      'Batch database operations where possible',
      'Use database views for complex queries',
      'Implement query result caching',
    ],
    automated: false,
    enabled: true,
  },
  {
    id: 'image-optimization',
    name: 'Dynamic Image Optimization',
    description: 'Optimize images based on device capabilities and network conditions',
    category: 'network',
    priority: 'medium',
    impact: 'medium',
    effort: 'low',
    targetMetrics: ['memoryUsage', 'screenTransitionTime'],
    implementation: [
      'Resize images based on device screen density',
      'Use WebP format when supported',
      'Implement progressive image loading',
      'Cache resized images locally',
    ],
    automated: true,
    enabled: true,
  },
  {
    id: 'network-optimization',
    name: 'Network Request Optimization',
    description: 'Optimize network requests for government portals',
    category: 'network',
    priority: 'medium',
    impact: 'medium',
    effort: 'low',
    targetMetrics: ['portalResponseTime', 'portalSuccessRate'],
    implementation: [
      'Implement request retry with exponential backoff',
      'Use connection pooling for portal requests',
      'Add request timeout optimization',
      'Cache portal metadata locally',
    ],
    automated: true,
    enabled: true,
  },
  {
    id: 'user-flow-optimization',
    name: 'User Flow Optimization',
    description: 'Optimize user flows based on behavior analytics',
    category: 'user-experience',
    priority: 'high',
    impact: 'high',
    effort: 'high',
    targetMetrics: ['userFlowCompletionRate'],
    implementation: [
      'Identify and reduce friction points',
      'Implement smart form pre-filling',
      'Add contextual help and guidance',
      'Optimize form field ordering based on usage',
    ],
    automated: false,
    enabled: true,
  },
  {
    id: 'error-reduction',
    name: 'Automated Error Reduction',
    description: 'Automatically handle and recover from common errors',
    category: 'user-experience',
    priority: 'high',
    impact: 'high',
    effort: 'medium',
    targetMetrics: ['errorRate', 'crashRate'],
    implementation: [
      'Implement automatic error recovery',
      'Add fallback mechanisms for critical operations',
      'Improve error messages and user guidance',
      'Use circuit breakers for external services',
    ],
    automated: true,
    enabled: true,
  },
];
