export const PORTAL_SUBMISSION_IDS = {
  screen: { id: 'portal-submission-screen', type: 'container' as const },
  closeButton: { id: 'close-portal-button', type: 'button' as const },
  progressBar: { id: 'progress-bar', type: 'container' as const },
  loadingIndicator: { id: 'portal-loading-indicator', type: 'container' as const },
  toolbarBackButton: { id: 'toolbar-back-button', type: 'button' as const },
  toolbarForwardButton: { id: 'toolbar-forward-button', type: 'button' as const },
  toolbarRefreshButton: { id: 'toolbar-refresh-button', type: 'button' as const },
  autoLoginProgressBanner: { id: 'auto-login-progress-banner', type: 'container' as const },
  autoLoginFailedBanner: { id: 'auto-login-failed-banner', type: 'container' as const },
  authPageBanner: { id: 'auth-page-banner', type: 'container' as const },
  captchaPageBanner: { id: 'captcha-page-banner', type: 'container' as const },
  autofillBanner: { id: 'autofill-banner', type: 'container' as const },
  lowFillWarningBanner: { id: 'low-fill-warning-banner', type: 'container' as const },
  manualGuideButton: { id: 'manual-guide-button', type: 'button' as const },
  saveCredentialsPrompt: { id: 'save-credentials-prompt', type: 'container' as const },
  portalWebview: { id: 'portal-webview', type: 'container' as const },
  autofillPill: { id: 'autofill-pill', type: 'container' as const },
  loadErrorOverlay: { id: 'load-error-overlay', type: 'container' as const },
  errorTryAgainButton: { id: 'error-try-again-button', type: 'button' as const },
  submitInAppSection: { id: 'submit-in-app-section', type: 'container' as const },
  incompleteFormMessage: { id: 'incomplete-form-message', type: 'container' as const },
  missingFieldsList: { id: 'missing-fields-list', type: 'container' as const },
  submitInAppButton: { id: 'submit-in-app-button', type: 'button' as const },
  toggleFieldsPanel: { id: 'toggle-fields-panel', type: 'button' as const },
  fieldsPanel: { id: 'fields-panel', type: 'container' as const },
  qrSaveOverlay: { id: 'qr-save-overlay', type: 'container' as const },
};
