export const RESTORE_BACKUP_IDS = {
  screen: { id: 'restore-backup-screen', type: 'ScrollView' as const },
  heading: { id: 'restore-backup-heading', type: 'Text' as const },
  stepIdle: { id: 'restore-step-idle', type: 'View' as const },
  pickFileButton: { id: 'pick-file-button', type: 'button' as const },
  stepPassphrase: { id: 'restore-step-passphrase', type: 'View' as const },
  passphraseField: { id: 'passphrase-field', type: 'TextInput' as const },
  toggleSecureEntry: { id: 'toggle-secure-entry', type: 'button' as const },
  submitPassphraseButton: { id: 'submit-passphrase-button', type: 'button' as const },
  cancelPassphraseButton: { id: 'cancel-passphrase-button', type: 'button' as const },
  stepLoading: { id: 'restore-step-loading', type: 'View' as const },
  stepConflict: { id: 'restore-step-conflict', type: 'View' as const },
  confirmReplaceButton: { id: 'confirm-replace-button', type: 'button' as const },
  cancelReplaceButton: { id: 'cancel-replace-button', type: 'button' as const },
  stepSuccess: { id: 'restore-step-success', type: 'View' as const },
  goToHomeButton: { id: 'go-to-home-button', type: 'button' as const },
  stepError: { id: 'restore-step-error', type: 'View' as const },
  errorMessage: { id: 'error-message', type: 'Text' as const },
  tryAgainButton: { id: 'try-again-button', type: 'button' as const },
};
