export const CREATE_TRIP_IDS = {
  tripNameField: { id: 'trip-name-field', type: 'Input' as const },
  createTripButton: { id: 'create-trip-button', type: 'button' as const, zone: 'footer' as const },
  addCompanionCtaButton: { id: 'add-companion-cta-button', type: 'button' as const },
  smartImportButton: { id: 'smart-import-button', type: 'button' as const },
  scanDestinationButton: { id: 'scan-destination-button', type: 'button' as const },
  addDestinationButton: { id: 'add-destination-button', type: 'button' as const },
  emptyStateScanButton: { id: 'empty-state-scan-button', type: 'button' as const },
  emptyStateAddButton: { id: 'empty-state-add-button', type: 'button' as const },
  legArrivalDate: { id: 'leg-${index}-arrival-date', type: 'DatePickerField' as const, dynamic: true as const },
  legDepartureDate: { id: 'leg-${index}-departure-date', type: 'DatePickerField' as const, dynamic: true as const },
  countrySelect: { id: 'country-select-${index}', type: 'SearchableSelect' as const, dynamic: true as const },
  removeLegButton: { id: 'remove-leg-${index}-button', type: 'button' as const, dynamic: true as const },
  applyToAllToggleRow: { id: 'apply-to-all-toggle-row', type: 'View' as const },
  applyToAllToggle: { id: 'apply-to-all-toggle', type: 'Toggle' as const },
  familyEmptyStateCard: { id: 'family-empty-state-card', type: 'Card' as const },
  legPassportValidityWarning: { id: 'create-trip-passport-validity-warning-${index}', type: 'View' as const, dynamic: true as const },
  legTravelersSynced: { id: 'leg-${index}-travelers-synced', type: 'View' as const, dynamic: true as const },
};
